### Get Server Status
GET http://localhost:3000/

### Create a New Post
POST http://localhost:3000/post
Content-Type: application/json

{
    "message": "This is my first post!",
    "sender": "Rony123"
}

### Get All Posts
GET http://localhost:3000/post

### Get Posts by Sender
GET http://localhost:3000/post?sender=Rony123

### Get Post by ID
GET http://localhost:3000/post/697e2973b7f35f90354f032e

### Update Post
PUT http://localhost:3000/post/697e2973b7f35f90354f032e
Content-Type: application/json

{
    "message": "This is the updated message!",
    "sender": "Rony123"
}

### --- Comments API ---

### Create a New Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
    "message": "Great post!",
    "sender": "PartnerUser",
    "postId": "697e33349f492d3ab797a433"
}

### Get All Comments
GET http://localhost:3000/comments

### Get Comments by Post ID
GET http://localhost:3000/comments?postId=697e33349f492d3ab797a433